[2023-09-20 21:25:48,537] ERROR log_exception() L1449 Exception on /documento [DELETE] - call_trace=/Users/macbook/Library/Python/3.9/lib/python/site-packages/flask/app.py L1449
Traceback (most recent call last):
  File "/Users/macbook/Library/Python/3.9/lib/python/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/macbook/Library/Python/3.9/lib/python/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/macbook/Library/Python/3.9/lib/python/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Users/macbook/Library/Python/3.9/lib/python/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/macbook/Library/Python/3.9/lib/python/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/macbook/Library/Python/3.9/lib/python/site-packages/flask_openapi3/scaffold.py", line 355, in wrapper
    resp = _do_wrapper(
  File "/Users/macbook/Library/Python/3.9/lib/python/site-packages/flask_openapi3/do_wrapper.py", line 135, in _do_wrapper
    response = func(**request_kwargs)
  File "/Users/macbook/Documents/Fullstack/TCC/fullstackbasico/backend/app.py", line 123, in del_documento
    print(documento_numero)
NameError: name 'documento_numero' is not defined
[2023-09-20 21:25:48,585] INFO _log() L224  127.0.0.1 - - [20/Sep/2023 21:25:48] "[35m[1mDELETE /documento?nr_documento=1234&razao_social=TESTE HTTP/1.1[0m" 500 - - call_trace=/Users/macbook/Library/Python/3.9/lib/python/site-packages/werkzeug/_internal.py L224 
[2023-09-20 21:25:55,472] INFO _log() L224  127.0.0.1 - - [20/Sep/2023 21:25:55] "GET /documentos HTTP/1.1" 200 - - call_trace=/Users/macbook/Library/Python/3.9/lib/python/site-packages/werkzeug/_internal.py L224 
[2023-09-20 21:26:47,476] INFO _log() L224  [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.15.171:5000 - call_trace=/Users/macbook/Library/Python/3.9/lib/python/site-packages/werkzeug/_internal.py L224 
[2023-09-20 21:26:47,476] INFO _log() L224  [33mPress CTRL+C to quit[0m - call_trace=/Users/macbook/Library/Python/3.9/lib/python/site-packages/werkzeug/_internal.py L224 
[2023-09-20 21:26:48,562] INFO _log() L224  127.0.0.1 - - [20/Sep/2023 21:26:48] "GET /documentos HTTP/1.1" 200 - - call_trace=/Users/macbook/Library/Python/3.9/lib/python/site-packages/werkzeug/_internal.py L224 
[2023-09-20 21:26:50,995] INFO _log() L224  127.0.0.1 - - [20/Sep/2023 21:26:50] "OPTIONS /documento?nr_documento=1234&razao_social=TESTE HTTP/1.1" 200 - - call_trace=/Users/macbook/Library/Python/3.9/lib/python/site-packages/werkzeug/_internal.py L224 
[2023-09-20 21:26:51,018] ERROR log_exception() L1449 Exception on /documento [DELETE] - call_trace=/Users/macbook/Library/Python/3.9/lib/python/site-packages/flask/app.py L1449
Traceback (most recent call last):
  File "/Users/macbook/Library/Python/3.9/lib/python/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/macbook/Library/Python/3.9/lib/python/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/macbook/Library/Python/3.9/lib/python/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Users/macbook/Library/Python/3.9/lib/python/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/macbook/Library/Python/3.9/lib/python/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/macbook/Library/Python/3.9/lib/python/site-packages/flask_openapi3/scaffold.py", line 355, in wrapper
    resp = _do_wrapper(
  File "/Users/macbook/Library/Python/3.9/lib/python/site-packages/flask_openapi3/do_wrapper.py", line 135, in _do_wrapper
    response = func(**request_kwargs)
  File "/Users/macbook/Documents/Fullstack/TCC/fullstackbasico/backend/app.py", line 134, in del_documento
    return {"mesage": "Documento removido", "id": documento_id}
NameError: name 'documento_id' is not defined
[2023-09-20 21:26:51,040] INFO _log() L224  127.0.0.1 - - [20/Sep/2023 21:26:51] "[35m[1mDELETE /documento?nr_documento=1234&razao_social=TESTE HTTP/1.1[0m" 500 - - call_trace=/Users/macbook/Library/Python/3.9/lib/python/site-packages/werkzeug/_internal.py L224 
[2023-09-20 21:26:53,744] INFO _log() L224  127.0.0.1 - - [20/Sep/2023 21:26:53] "GET /documentos HTTP/1.1" 200 - - call_trace=/Users/macbook/Library/Python/3.9/lib/python/site-packages/werkzeug/_internal.py L224 
[2023-09-20 21:26:54,915] INFO _log() L224  127.0.0.1 - - [20/Sep/2023 21:26:54] "GET /documentos HTTP/1.1" 200 - - call_trace=/Users/macbook/Library/Python/3.9/lib/python/site-packages/werkzeug/_internal.py L224 
[2023-09-20 21:28:21,577] INFO _log() L224  [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.15.171:5000 - call_trace=/Users/macbook/Library/Python/3.9/lib/python/site-packages/werkzeug/_internal.py L224 
[2023-09-20 21:28:21,577] INFO _log() L224  [33mPress CTRL+C to quit[0m - call_trace=/Users/macbook/Library/Python/3.9/lib/python/site-packages/werkzeug/_internal.py L224 
[2023-09-20 21:28:24,448] INFO _log() L224  127.0.0.1 - - [20/Sep/2023 21:28:24] "GET /documentos HTTP/1.1" 200 - - call_trace=/Users/macbook/Library/Python/3.9/lib/python/site-packages/werkzeug/_internal.py L224 
[2023-09-20 21:28:31,239] INFO _log() L224  127.0.0.1 - - [20/Sep/2023 21:28:31] "POST /documento HTTP/1.1" 200 - - call_trace=/Users/macbook/Library/Python/3.9/lib/python/site-packages/werkzeug/_internal.py L224 
[2023-09-20 21:28:44,876] INFO _log() L224  127.0.0.1 - - [20/Sep/2023 21:28:44] "POST /documento HTTP/1.1" 200 - - call_trace=/Users/macbook/Library/Python/3.9/lib/python/site-packages/werkzeug/_internal.py L224 
[2023-09-20 21:28:52,655] INFO _log() L224  127.0.0.1 - - [20/Sep/2023 21:28:52] "OPTIONS /documento?nr_documento=123&razao_social=teste HTTP/1.1" 200 - - call_trace=/Users/macbook/Library/Python/3.9/lib/python/site-packages/werkzeug/_internal.py L224 
[2023-09-20 21:28:52,678] INFO _log() L224  127.0.0.1 - - [20/Sep/2023 21:28:52] "DELETE /documento?nr_documento=123&razao_social=teste HTTP/1.1" 200 - - call_trace=/Users/macbook/Library/Python/3.9/lib/python/site-packages/werkzeug/_internal.py L224 
[2023-09-20 21:30:28,213] INFO _log() L224  127.0.0.1 - - [20/Sep/2023 21:30:28] "GET /documentos HTTP/1.1" 200 - - call_trace=/Users/macbook/Library/Python/3.9/lib/python/site-packages/werkzeug/_internal.py L224 
[2023-09-20 21:30:34,288] INFO _log() L224  127.0.0.1 - - [20/Sep/2023 21:30:34] "GET /documentos HTTP/1.1" 200 - - call_trace=/Users/macbook/Library/Python/3.9/lib/python/site-packages/werkzeug/_internal.py L224 
[2023-09-20 21:30:39,364] INFO _log() L224  127.0.0.1 - - [20/Sep/2023 21:30:39] "GET /documentos HTTP/1.1" 200 - - call_trace=/Users/macbook/Library/Python/3.9/lib/python/site-packages/werkzeug/_internal.py L224 
[2023-09-20 21:38:27,837] INFO _log() L224  127.0.0.1 - - [20/Sep/2023 21:38:27] "GET /documentos HTTP/1.1" 200 - - call_trace=/Users/macbook/Library/Python/3.9/lib/python/site-packages/werkzeug/_internal.py L224 
[2023-09-20 21:38:56,090] INFO _log() L224  127.0.0.1 - - [20/Sep/2023 21:38:56] "[31m[1mGET /documento?nr_documento=undefined&razao_social=undefined HTTP/1.1[0m" 422 - - call_trace=/Users/macbook/Library/Python/3.9/lib/python/site-packages/werkzeug/_internal.py L224 
[2023-09-20 21:39:02,908] INFO _log() L224  127.0.0.1 - - [20/Sep/2023 21:39:02] "[31m[1mGET /documento?nr_documento=undefined&razao_social=undefined HTTP/1.1[0m" 422 - - call_trace=/Users/macbook/Library/Python/3.9/lib/python/site-packages/werkzeug/_internal.py L224 
[2023-09-20 21:39:21,031] INFO _log() L224  127.0.0.1 - - [20/Sep/2023 21:39:21] "GET /documentos HTTP/1.1" 200 - - call_trace=/Users/macbook/Library/Python/3.9/lib/python/site-packages/werkzeug/_internal.py L224 
[2023-09-20 21:40:50,724] INFO _log() L224  127.0.0.1 - - [20/Sep/2023 21:40:50] "GET /documentos HTTP/1.1" 200 - - call_trace=/Users/macbook/Library/Python/3.9/lib/python/site-packages/werkzeug/_internal.py L224 
