[2023-09-18 14:42:57,777] INFO _log() L224  [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.15.171:5000 - call_trace=/Users/macbook/Library/Python/3.9/lib/python/site-packages/werkzeug/_internal.py L224 
[2023-09-18 14:42:57,778] INFO _log() L224  [33mPress CTRL+C to quit[0m - call_trace=/Users/macbook/Library/Python/3.9/lib/python/site-packages/werkzeug/_internal.py L224 
[2023-09-18 14:43:10,397] INFO _log() L224  192.168.15.171 - - [18/Sep/2023 14:43:10] "[32mGET / HTTP/1.1[0m" 302 - - call_trace=/Users/macbook/Library/Python/3.9/lib/python/site-packages/werkzeug/_internal.py L224 
[2023-09-18 14:43:10,420] INFO _log() L224  192.168.15.171 - - [18/Sep/2023 14:43:10] "[32mGET /openapi HTTP/1.1[0m" 308 - - call_trace=/Users/macbook/Library/Python/3.9/lib/python/site-packages/werkzeug/_internal.py L224 
[2023-09-18 14:43:10,454] INFO _log() L224  192.168.15.171 - - [18/Sep/2023 14:43:10] "GET /openapi/ HTTP/1.1" 200 - - call_trace=/Users/macbook/Library/Python/3.9/lib/python/site-packages/werkzeug/_internal.py L224 
[2023-09-18 14:43:10,514] INFO _log() L224  192.168.15.171 - - [18/Sep/2023 14:43:10] "GET /openapi/static/images/swagger.svg HTTP/1.1" 200 - - call_trace=/Users/macbook/Library/Python/3.9/lib/python/site-packages/werkzeug/_internal.py L224 
[2023-09-18 14:43:10,517] INFO _log() L224  192.168.15.171 - - [18/Sep/2023 14:43:10] "GET /openapi/static/images/redoc.svg HTTP/1.1" 200 - - call_trace=/Users/macbook/Library/Python/3.9/lib/python/site-packages/werkzeug/_internal.py L224 
[2023-09-18 14:43:10,528] INFO _log() L224  192.168.15.171 - - [18/Sep/2023 14:43:10] "GET /openapi/static/images/rapidoc.svg HTTP/1.1" 200 - - call_trace=/Users/macbook/Library/Python/3.9/lib/python/site-packages/werkzeug/_internal.py L224 
[2023-09-18 14:43:10,572] INFO _log() L224  192.168.15.171 - - [18/Sep/2023 14:43:10] "[33mGET /apple-touch-icon-precomposed.png HTTP/1.1[0m" 404 - - call_trace=/Users/macbook/Library/Python/3.9/lib/python/site-packages/werkzeug/_internal.py L224 
[2023-09-18 14:43:10,578] INFO _log() L224  192.168.15.171 - - [18/Sep/2023 14:43:10] "[33mGET /apple-touch-icon.png HTTP/1.1[0m" 404 - - call_trace=/Users/macbook/Library/Python/3.9/lib/python/site-packages/werkzeug/_internal.py L224 
[2023-09-18 14:43:11,500] INFO _log() L224  192.168.15.171 - - [18/Sep/2023 14:43:11] "GET /openapi/static/images/apidoc.svg HTTP/1.1" 200 - - call_trace=/Users/macbook/Library/Python/3.9/lib/python/site-packages/werkzeug/_internal.py L224 
[2023-09-18 14:43:12,014] INFO _log() L224  192.168.15.171 - - [18/Sep/2023 14:43:12] "GET /openapi/swagger HTTP/1.1" 200 - - call_trace=/Users/macbook/Library/Python/3.9/lib/python/site-packages/werkzeug/_internal.py L224 
[2023-09-18 14:43:12,058] INFO _log() L224  192.168.15.171 - - [18/Sep/2023 14:43:12] "GET /openapi/static/css/swagger-ui.css HTTP/1.1" 200 - - call_trace=/Users/macbook/Library/Python/3.9/lib/python/site-packages/werkzeug/_internal.py L224 
[2023-09-18 14:43:12,062] INFO _log() L224  192.168.15.171 - - [18/Sep/2023 14:43:12] "GET /openapi/static/js/swagger-ui-bundle.js HTTP/1.1" 200 - - call_trace=/Users/macbook/Library/Python/3.9/lib/python/site-packages/werkzeug/_internal.py L224 
[2023-09-18 14:43:12,077] INFO _log() L224  192.168.15.171 - - [18/Sep/2023 14:43:12] "GET /openapi/static/js/swagger-ui-standalone-preset.js HTTP/1.1" 200 - - call_trace=/Users/macbook/Library/Python/3.9/lib/python/site-packages/werkzeug/_internal.py L224 
[2023-09-18 14:43:12,395] INFO _log() L224  192.168.15.171 - - [18/Sep/2023 14:43:12] "GET /openapi/openapi.json HTTP/1.1" 200 - - call_trace=/Users/macbook/Library/Python/3.9/lib/python/site-packages/werkzeug/_internal.py L224 
[2023-09-18 14:43:12,449] INFO _log() L224  192.168.15.171 - - [18/Sep/2023 14:43:12] "[36mGET /openapi/static/images/swagger.svg HTTP/1.1[0m" 304 - - call_trace=/Users/macbook/Library/Python/3.9/lib/python/site-packages/werkzeug/_internal.py L224 
[2023-09-18 14:44:40,628] INFO _log() L224  127.0.0.1 - - [18/Sep/2023 14:44:40] "GET /documentos HTTP/1.1" 200 - - call_trace=/Users/macbook/Library/Python/3.9/lib/python/site-packages/werkzeug/_internal.py L224 
[2023-09-18 14:44:56,610] INFO _log() L224  127.0.0.1 - - [18/Sep/2023 14:44:56] "POST /documento HTTP/1.1" 200 - - call_trace=/Users/macbook/Library/Python/3.9/lib/python/site-packages/werkzeug/_internal.py L224 
[2023-09-18 14:45:08,996] ERROR log_exception() L1449 Exception on /documentos [GET] - call_trace=/Users/macbook/Library/Python/3.9/lib/python/site-packages/flask/app.py L1449
Traceback (most recent call last):
  File "/Users/macbook/Library/Python/3.9/lib/python/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/macbook/Library/Python/3.9/lib/python/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/macbook/Library/Python/3.9/lib/python/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Users/macbook/Library/Python/3.9/lib/python/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/macbook/Library/Python/3.9/lib/python/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/macbook/Library/Python/3.9/lib/python/site-packages/flask_openapi3/scaffold.py", line 109, in wrapper
    resp = _do_wrapper(
  File "/Users/macbook/Library/Python/3.9/lib/python/site-packages/flask_openapi3/do_wrapper.py", line 135, in _do_wrapper
    response = func(**request_kwargs)
  File "/Users/macbook/Documents/Fullstack/TCC/fullstackbasico/backend/app.py", line 79, in get_documentos
    return apresenta_documento(documento), 200
  File "/Users/macbook/Documents/Fullstack/TCC/fullstackbasico/backend/schemas/documento.py", line 73, in apresenta_documento
    "id": documento.id,
AttributeError: module 'schemas.documento' has no attribute 'id'
[2023-09-18 14:45:09,053] INFO _log() L224  127.0.0.1 - - [18/Sep/2023 14:45:09] "[35m[1mGET /documentos HTTP/1.1[0m" 500 - - call_trace=/Users/macbook/Library/Python/3.9/lib/python/site-packages/werkzeug/_internal.py L224 
[2023-09-18 14:48:20,103] INFO _log() L224  [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.15.171:5000 - call_trace=/Users/macbook/Library/Python/3.9/lib/python/site-packages/werkzeug/_internal.py L224 
[2023-09-18 14:48:20,104] INFO _log() L224  [33mPress CTRL+C to quit[0m - call_trace=/Users/macbook/Library/Python/3.9/lib/python/site-packages/werkzeug/_internal.py L224 
[2023-09-18 14:48:23,232] ERROR log_exception() L1449 Exception on /documentos [GET] - call_trace=/Users/macbook/Library/Python/3.9/lib/python/site-packages/flask/app.py L1449
Traceback (most recent call last):
  File "/Users/macbook/Library/Python/3.9/lib/python/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/macbook/Library/Python/3.9/lib/python/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/macbook/Library/Python/3.9/lib/python/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Users/macbook/Library/Python/3.9/lib/python/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/macbook/Library/Python/3.9/lib/python/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/macbook/Library/Python/3.9/lib/python/site-packages/flask_openapi3/scaffold.py", line 109, in wrapper
    resp = _do_wrapper(
  File "/Users/macbook/Library/Python/3.9/lib/python/site-packages/flask_openapi3/do_wrapper.py", line 135, in _do_wrapper
    response = func(**request_kwargs)
  File "/Users/macbook/Documents/Fullstack/TCC/fullstackbasico/backend/app.py", line 79, in get_documentos
    return apresenta_documento(documento), 200
  File "/Users/macbook/Documents/Fullstack/TCC/fullstackbasico/backend/schemas/documento.py", line 72, in apresenta_documento
    "id": documento.id,
AttributeError: module 'schemas.documento' has no attribute 'id'
[2023-09-18 14:48:23,272] INFO _log() L224  127.0.0.1 - - [18/Sep/2023 14:48:23] "[35m[1mGET /documentos HTTP/1.1[0m" 500 - - call_trace=/Users/macbook/Library/Python/3.9/lib/python/site-packages/werkzeug/_internal.py L224 
[2023-09-19 21:51:34,422] INFO _log() L224  [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.15.171:5000 - call_trace=/Users/macbook/Library/Python/3.9/lib/python/site-packages/werkzeug/_internal.py L224 
[2023-09-19 21:51:34,423] INFO _log() L224  [33mPress CTRL+C to quit[0m - call_trace=/Users/macbook/Library/Python/3.9/lib/python/site-packages/werkzeug/_internal.py L224 
[2023-09-19 21:51:39,870] INFO _log() L224  192.168.15.171 - - [19/Sep/2023 21:51:39] "[32mGET / HTTP/1.1[0m" 302 - - call_trace=/Users/macbook/Library/Python/3.9/lib/python/site-packages/werkzeug/_internal.py L224 
